services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pimcorecasts\Bundle\N8nManager\Command\:
        resource: '../../Command/*'
        tags: [ 'console.command' ]

    Pimcorecasts\Bundle\N8nManager\Controller\:
        resource: '../../Controller'
        public: true
        tags: [ 'controller.service_arguments' ]

    Pimcorecasts\Bundle\N8nManager\Service\:
        resource: '../../Service'
        public: true

    Pimcorecasts\Bundle\N8nManager\Twig\:
        resource: '../../Twig'
        tags: [twig.extension]