services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pimcorecasts\Bundle\N8nManager\Command\:
        resource: '../Command/*'
        public: true
        tags: [ 'console.command' ]

    Pimcorecasts\Bundle\N8nManager\Controller\:
        resource: '../Controller'
        public: true
        tags: [ 'controller.service_arguments' ]